apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datacatalog-backend.fullname" . }}-drm
  labels:
    {{- include "datacatalog-backend-drm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.drmDeployment.autoscaling.enabled }}
  replicas: {{ .Values.drmDeployment.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.drmDeployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "datacatalog-backend-drm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.drmDeployment.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datacatalog-backend-drm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.drmDeployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.drmDeployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.drmDeployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.drmDeployment.securityContext | nindent 12 }}
          image: "{{ .Values.drmDeployment.image.repository }}:{{ .Values.drmDeployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.drmDeployment.image.pullPolicy }}
          env:
          {{ range $k, $v := .Values.drmDeployment.env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
          {{- end }}
          {{- with .Values.drmDeployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.drmDeployment.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.drmDeployment.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.drmDeployment.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.drmDeployment.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.drmDeployment.resources | nindent 12 }}
      {{- with .Values.drmDeployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.drmDeployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.drmDeployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
