apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datacatalog-backend.fullname" . }}
  labels:
    {{- include "datacatalog-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "datacatalog-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.secretName }}-reader"
        vault.hashicorp.com/auth-path: "auth/kubernetes-{{ .Values.environment }}"
        vault.hashicorp.com/agent-inject-secret-appsettings.secrets.json: "{{ .Values.secretName }}/data/credentials"
        vault.hashicorp.com/agent-inject-template-appsettings.secrets.json: |
          {{`{{-`}} with secret "{{ .Values.secretName }}/data/credentials" {{`-}}`}}
          {{`{
            "GroupManagementClientId": "{{ .Data.data.client_id }}",
            "GroupManagementClientSecret": "{{ .Data.data.secret }}",
            "ConnectionStrings": {
              "DataCatalog": "{{ .Data.data.connection_string }}",
              "ServiceBus": "{{ .Data.data.service_bus_connection_string }}"
            },
            "AzureAd": {
              "TenantId": "{{ .Data.data.tenant_id }}",
              "ClientId": "{{ .Data.data.client_id }}",
              "ClientSecret": "{{ .Data.data.secret }}"
            }
          }
          {{- end -}}`}}
      {{- with .Values.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datacatalog-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          env:
          {{ range $k, $v := .Values.deployment.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
