{{- if .Values.job.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "datacatalog-backend.fullname" . }}-migrator-job
  labels:
    {{- include "datacatalog-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "datacatalog-backend.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        env:
          {{ range $k, $v := .Values.job.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
        {{- with .Values.job.volumeMounts }}
        volumeMounts:
          {{ . }}
        {{- end -}}
{{- end -}}