{{- if .Values.job.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "datacatalog-backend.fullname" . }}-migrator-job
  labels:
    {{- include "datacatalog-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: "{{ .Values.secretName }}-reader"
        vault.hashicorp.com/auth-path: "auth/kubernetes-{{ .Values.environment }}"
        vault.hashicorp.com/agent-inject-secret-appsettings.secrets.json: "{{ .Values.secretName }}/data/credentials"
        vault.hashicorp.com/agent-inject-template-appsettings.secrets.json: |
          {{`{{-`}} with secret "{{ .Values.secretName }}/data/credentials" {{`-}}`}}
          {{`{
            "ConnectionStrings": {
              "DataCatalog": "{{ .Data.data.connection_string }}"
            }
          }
          {{- end -}}`}}
      labels:
        {{- include "datacatalog-backend.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        env:
          {{ range $k, $v := .Values.job.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
{{- end -}}