apiVersion: v1
kind: Service
metadata:
  name: {{ include "datacatalog-backend.fullname" . }}-svc
  annotations:
    prometheus.io/port: '80'
    prometheus.io/scrape: 'true'
  labels:
    {{- include "datacatalog-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "datacatalog-backend.selectorLabels" . | nindent 4 }}
