using System;
using AutoFixture;
using AutoFixture.AutoMoq;
using AutoFixture.Xunit2;

namespace DataCatalog.DatasetResourceManagement.UnitTests.AutoMoqData
{
    /// <summary>
    /// Provides auto-generated data specimens generated by AutoFixture as an extension to xUnit's Theory attribute and enables auto-mocking with Moq.
    /// </summary>
    public class MoqAutoDataAttribute : AutoDataAttribute
    {
        private MoqAutoDataAttribute(bool configureMembers, Func<IFixture> fixtureFactory)
            : base(() => fixtureFactory().Customize(new AutoMoqCustomization
            {
                ConfigureMembers = configureMembers
            }))
        {
        }

        protected MoqAutoDataAttribute(Func<IFixture> fixtureFactory)
            : this(true, fixtureFactory)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="T:Energinet.DataPlatform.Shared.Testing.AutoFixture.MoqAutoDataAttribute" /> class with the specified mocking behaviour for its members.
        /// </summary>
        /// <param name="configureMembers">Specifies whether mocked members will be setup to automatically retrieve the return values from a fixture.</param>
        private MoqAutoDataAttribute(bool configureMembers)
            : this(configureMembers, () => new Fixture())
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="T:Energinet.DataPlatform.Shared.Testing.AutoFixture.MoqAutoDataAttribute" /> class where the behaviour of its mocked members is to retrieve the return values from a fixture.
        /// </summary>
        public MoqAutoDataAttribute()
            : this(true)
        {
        }
    }
}